#Количество нод, не должно быть кратно 2.
NodeCount = 3

#Кол-во ГБ на нодах
VolumeSize = 200

#Кол-во ОЗУ
MemorySize = 2048

#Кол-во ЦПУ
CpuSize = 1


Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # ceph-node-1.
  (1..NodeCount).each do |i|
  config.vm.define "ceph-node-#{i}" do |cn1|
    cn1.vm.hostname = "ceph-node-#{i}"
    cn1.vm.box = "geerlingguy/centos7"
    cn1.vm.network :private_network, ip: "172.16.2.1#{i}"
    cn1.newdisk.size = MemorySize * 1024 # size in megabytes
    cn1.newdisk.path = "ceph-node-#{i}.vdi"
        
    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = GpuSize
      v.cpus = CpuSize
      
    end
  end

    # Python3 for ansible

    config.vm.provision "shell", inline: <<-SHELL
        yum update
        yum -y install python 2
        yum -y sshpass git
        
     SHELL
    config.vm.provision "shell", path: "bootstrap_ceph.sh"

    
end

